// Copyright (c) 2026 Ali-Eimaan. MIT License.
//
// SKELETON — no implementation. See IMPLEMENTATION_GUIDE.md §6.
//
// This is the ONLY translation unit allowed to include acados headers. Guard every acados
// include with UAV_MPC_WITH_ACADOS so the package still builds (with a stub backend)
// on a machine without acados — CI's format/lint job depends on that.

#include "uav_mpc/acados_wrapper.hpp"

#include <chrono>
#include <string>
#include <vector>

#ifdef UAV_MPC_WITH_ACADOS
// clang-format off
#include "acados/utils/print.h"
#include "acados_c/ocp_nlp_interface.h"
#include "acados_solver_quadrotor.h"   // generated by codegen/generate_acados_solver.py
// clang-format on
#endif

namespace uav_mpc
{

/// PIMPL body. Holds the raw acados handles; empty when built without acados.
struct AcadosWrapper::Impl
{
#ifdef UAV_MPC_WITH_ACADOS
  quadrotor_solver_capsule * capsule{nullptr};
  ocp_nlp_config * nlp_config{nullptr};
  ocp_nlp_dims * nlp_dims{nullptr};
  ocp_nlp_in * nlp_in{nullptr};
  ocp_nlp_out * nlp_out{nullptr};
  ocp_nlp_solver * nlp_solver{nullptr};
  void * nlp_opts{nullptr};
#endif
  std::vector<double> yref_buffer;   ///< scratch, sized nx+nu, reused every tick (no malloc)
  std::vector<double> x_buffer;      ///< scratch, sized nx
  std::vector<double> u_buffer;      ///< scratch, sized nu
};

AcadosWrapper::AcadosWrapper()
: impl_(std::make_unique<Impl>())
{
}

AcadosWrapper::~AcadosWrapper()
{
  // TODO(deepseek): shutdown() — must be idempotent and must not throw.
}

AcadosWrapper::AcadosWrapper(AcadosWrapper &&) noexcept = default;
AcadosWrapper & AcadosWrapper::operator=(AcadosWrapper &&) noexcept = default;

bool AcadosWrapper::initialise(const SolverConfig & /*config*/, std::string * /*error*/)
{
  // TODO(deepseek):
  //   1. quadrotor_acados_create(capsule) and check the return code
  //   2. pull nx/nu/np from nlp_dims; store into nx_/nu_/np_
  //   3. hard-fail if config.horizon_steps != QUADROTOR_N or |Tf - codegen Tf| > 1e-9
  //   4. hard-fail if generatedModelHash() != the hash recorded in codegen/MODEL_HASH
  //   5. apply setWeights(); zero the parameter vector on every stage
  //   6. resize the Impl scratch buffers
  // Without acados (stub build): fill nx_/nu_ from config sizes and return true so unit tests
  // that never solve still link.
  return false;
}

void AcadosWrapper::shutdown()
{
  // TODO(deepseek): quadrotor_acados_free() + quadrotor_acados_free_capsule(), null the
  // handles, set initialised_ = false.
}

void AcadosWrapper::setInitialState(const Eigen::VectorXd & /*x0*/)
{
  // TODO(deepseek): ocp_nlp_constraints_model_set(..., 0, "lbx"/"ubx", x0). Assert size == nx_.
}

void AcadosWrapper::setStageReference(
  int /*stage*/, const Eigen::VectorXd & /*x_ref*/, const Eigen::VectorXd & /*u_ref*/)
{
  // TODO(deepseek): pack [x_ref; u_ref] into impl_->yref_buffer, then
  // ocp_nlp_cost_model_set(..., stage, "yref", buffer).
}

void AcadosWrapper::setTerminalReference(const Eigen::VectorXd & /*x_ref*/)
{
  // TODO(deepseek): stage N, field "yref" of size nx.
}

void AcadosWrapper::setReferenceHorizon(
  const std::vector<Eigen::VectorXd> & /*x_refs*/, const std::vector<Eigen::VectorXd> & /*u_refs*/)
{
  // TODO(deepseek): loop 0..N-1 + terminal. Sizes must be N+1 and N.
}

void AcadosWrapper::setParameters(const Eigen::VectorXd & /*p*/)
{
  // TODO(deepseek): quadrotor_acados_update_params() on every stage 0..N.
}

void AcadosWrapper::setWeights(
  const Eigen::VectorXd & /*q_diag*/, const Eigen::VectorXd & /*r_diag*/,
  const Eigen::VectorXd & /*q_terminal_diag*/)
{
  // TODO(deepseek): build the dense diagonal W ((nx+nu)^2) and W_e (nx^2) row-major buffers and
  // push them to every stage. Validate that the diagonals are non-negative and that Q_N is
  // at least as large as Q (a smaller terminal weight is the classic cause of horizon-end drift).
}

SolveResult AcadosWrapper::solve()
{
  // TODO(deepseek):
  //   t0 = steady_clock::now()
  //   status = quadrotor_acados_solve(capsule)
  //   read "time_tot", "sqp_iter", "residuals"/"cost_value" from nlp_out via ocp_nlp_get
  //   map the acados int status onto SolverStatus
  //   on failure: bump consecutive_failures_, and if this is the first failure re-init the
  //     guess (resetToHover on the current x0) and solve exactly once more
  //   on success: consecutive_failures_ = 0
  // Never throw — this runs inside the 100 Hz timer.
  return SolveResult{};
}

Eigen::VectorXd AcadosWrapper::optimalInput() const
{
  // TODO(deepseek): ocp_nlp_out_get(..., 0, "u", buffer).
  return Eigen::VectorXd::Zero(nu_);
}

Eigen::VectorXd AcadosWrapper::predictedState(int /*stage*/) const
{
  // TODO(deepseek): ocp_nlp_out_get(..., stage, "x", buffer). Clamp stage to [0, N].
  return Eigen::VectorXd::Zero(nx_);
}

std::vector<Eigen::VectorXd> AcadosWrapper::predictedTrajectory() const
{
  // TODO(deepseek): N+1 states.
  return {};
}

void AcadosWrapper::resetToHover(const Eigen::VectorXd & /*x0*/, double /*hover_thrust_per_rotor*/)
{
  // TODO(deepseek): set every stage's "x" guess to x0 with zeroed velocity/rates, every "u"
  // guess to the hover thrust, and zero "lam"/"pi". This is the recovery path — keep it
  // allocation-free.
}

void AcadosWrapper::shiftWarmStart()
{
  // TODO(deepseek): x_k <- x_{k+1} for k in [0, N-1], x_N unchanged; likewise for u.
  // Skip when config_.shift_on_warm_start is false.
}

std::string AcadosWrapper::generatedModelHash()
{
  // TODO(deepseek): return the UAV_MPC_MODEL_HASH macro that generate_acados_solver.py
  // writes into codegen_output/include/model_hash.h. Return "" in the stub build.
  return {};
}

}  // namespace uav_mpc
